{% set name = "isodate" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4cd1aa0f43ca76f4a6c6c0292a85f40b35ec2e43e315b59f06e6d32171a953e6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - isodate
  requires: 
    - pip
    - pytest
  commands: 
    - pip check
    - pytest tests

about:
  home: https://github.com/gweis/isodate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An ISO 8601 date/time/duration parser and formatter.
  description: |
    This module implements ISO 8601 date, time and duration parsing. The
    implementation follows ISO8601:2004 standard, and implements only date/time
    representations mentioned in the standard.
  dev_url: https://github.com/gweis/isodate
  doc_url: https://github.com/gweis/isodate

extra:
  recipe-maintainers:
    - ocefpaf
