travis:
  secure:
    BINSTAR_TOKEN: urtFSTTUSLuowV9KGqP9MZnKfG6c/HtzPeQhbyWztNnXwxwRvMupm+wBtROoE1Xmgo+I1mRYddUwmBYuLjsFfMD8S14xRA5Ri30O6O5GP1pAQAksBgjE8rtuoTH+mNfNs1DzyiHzOnr8veM/8JgBP1rQq33mj2ImYmPzAHOa0xhou3Q94/+REQmRWe9cAPjnyob1PCe2c/17LmXPrdXxYY89CdmweTGIcoS3a4r5Alazdyfkh6hWKXSvo6CgC237BmYGjZDJHrnmqAZeeId73UYA1KcAJJZAX7fFKICJG3I59hB9quD/fOWOCV/D5Oq9fjXjU9/NuzZNyGTF+EuyY5AqrHwrdq8AsaSys3Ol92+Vnch6mVG6az9ja+lthEtHXKf1UpWzvJKxFtcEkkWWqfQMyaDRiphiN8hx0qXzZD+Bw513umtXbm2PS1VkXHkrDZRgCS8PmVXdENOxGCNN0yeWIKx1y4BySE/T1Oq3jmQUeSTSzTK7yqyemg0BEydT+P6LW4DyQdSbULsO6FpX+gs3EPDsEBt/egp4h0NFs40xETDQvh6LGrPU4RxL7XQ83hVhQ+/5A0bYNNZUwRHZ8F4uFvryChHWnmz6FN5dcq3HkHs3+UYda918dGpdBkHZAys0Eaw2UVBSpaFd+TIXzuZyg9EqynrnD8oJURTZbNU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
