travis:
  secure:
    BINSTAR_TOKEN: mbSbT/q9Xl57rxWR/ljgqKWSkrAcvQcdEUa8aiXCSlJxSY2uCsJ5vcAWwVKZD42w388bFqydh8YV580ksUHvTm96Gx7xt2vmhY7hDFqP7MSDz94XXAlAsZDDsHMq9GsmGYvNJFtx3Kk+lyIlB1qh0+TL82zmMQbNOC9lJTo/v8nHhznCNrYoe77E914ZYWFjQJObPeHz04m9lDZG2lSnRyROcNbZkhyhe/lrPBlnci/6qr6+/yOES73oL3j66JKMIvZYxTQCaI9KibUnTApzpFE1uMaI/KPw9gXXzGhYwR3117UGf4TNjMkVCyfYpllLWEv7b/hP3z8urVQlDaRVhdAuBEeG9hhtGr1szrE0Dk6FsXpA6SpkLlHpgrSRDY+JW1xvjfJTg2BcrV76yzYU5EERAv/R3KBFd/S/txoTj9EsClU0zlVTgESrw872GPHxjdo8TsvMXihDxAMxiadjQvRDesj/8nIAhw12RHDMTOmqJBUB6dHf6yvPZZv6oXfojcAYb8s3aZ7uyfPErJltM5RzMQriEbUXDFnawV/G3FwSwN7qLxqVLksbZZODo49NBOcvKv/yT7CfCmWPJrG7BmTtLeV5O2qxRIt8t5HeZ/aJiyJC3wD6qyhp+kGY1NB2wG96wG9WVVrJNOHwGbFf3EJRlvc1JI+xYpqwJE7mCmE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
